CREATE TABLE `dw_export_settings`
(
	`ID` int NOT NULL AUTO_INCREMENT,
	`IS_DONE` varchar(1) NULL DEFAULT 'N',
	`TABLE_NAME` varchar(255) NOT NULL,
	`COLUMN_NAME` varchar(255) NOT NULL,
	`START_VALUE` varchar(255) NULL,
	`FINISH_VALUE` varchar(255) NULL,
	`START_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`LAST_START_AT` TIMESTAMP,
	`REPEAT` varchar(1) NULL DEFAULT 'N',
	`REPEAT_TIME` integer NOT NULL DEFAULT 0,
	
	PRIMARY KEY (ID)
);

CREATE TABLE `dw_export_log`
(
	`ID` int NOT NULL AUTO_INCREMENT,
	`TABLE_NAME` varchar(255) NOT NULL,
	`RULE_ID` integer NOT NULL,
	`DUMP_FILE_NAME` varchar(1024) NOT NULL,
	`DIRECTION` varchar(10) NOT NULL DEFAULT 'Экспорт',
	`UPDATE_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	
	PRIMARY KEY (ID)
);